import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className="flex">
      <Head>
        <title>YourBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex">
        <h1 className="text-xl font-medium text-orange">
          Welcome in Your Blog page
        </h1>

        <Link href="/about">check about me page</Link>
      </main>

      <footer className="grid">
        <p>welcome</p>
      </footer>
    </div>
  );
};

export default Home;
